### PR TITLE
Updated all the things

### PR DESCRIPTION
**Pull request by phit**
I tested with NodeJS 8.9.1 LTS

For Docker
https://github.com/MultiMC/MultiMC-salt/blob/master/salt/docker/mmc-bbot/mmc-env-ubu64/Dockerfile#L13-L19
should be
```
# Install node.js
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt-get install -y nodejs

# Install the site builder packages
RUN npm install -g grunt-cli
RUN npm install -g docpad@6.79.4
```

### CODE REVIEW

**Comment by peterix** [comment]
Alright. I'll have to rebuild the images again. I built them with 4.x.

Also, that's a lot of changes. Mostly red, so that must be good :+1:
Once I have the images for this, I'll just push it to http://test.multimc.org/ and check for differences.

**Comment by phit** [comment]
4.x should be okay too, but might as well go for latest to future proof ;)
So many deletions because I removed [this folder](https://github.com/MultiMC/MultiMC-Website/tree/develop/uikit/dist) from git, as it is regenerated every time by the build script anyway.

**Comment by peterix** [comment]
Tried to build it with the current image.

The build produced an immense amount of errors:
http://ci.multimc.org/builders/site/builds/73/steps/compile/logs/stdio

It seems to be alive:
http://test.multimc.org/

But doesn't really look right. I'll go rebuild that image with node 8 and new deps.

**Comment by peterix** [comment]
image

It went abstract and broke page rendering in chromium.
It crashed.

**Comment by peterix** [comment]
Reverted develop back to master... now it's no longer taking forever, but the results are the same:
http://ci.multimc.org/builders/site/builds/76
http://test.multimc.org/

... OK. I think I need a website that doesn't involve all this javascript madness.

**Pull request merged**
